# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.107:3306/hjc-api
    username: hjc-API
    password: w5JBCSFFGjhY3erC
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 192.168.10.107
    port: 6379
    timeout: 5000
    password: bPnP7c3yAaBymaE2
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: 192.168.10.107:9200
    username: elastic
    password: Cp_tdebFg=y+olKvev6C
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
houapi:
  client:
    access-key: qwe123
    secret-key: qwe456